# Generated by Django 3.0.3 on 2021-03-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('lastDegree', models.CharField(max_length=50)),
                ('degreeName', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('dateOfJoining', models.DateField()),
                ('dateofEnd', models.DateField()),
                ('favSport', models.CharField(max_length=50)),
                ('interest', models.CharField(max_length=50)),
                ('shortBio', models.TextField()),
            ],
        ),
    ]
