# Generated by Django 3.0.3 on 2021-03-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='favSport',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='institute',
            new_name='university',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='lastDegree',
        ),
    ]
