# Generated by Django 3.0.3 on 2021-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210303_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='dateOfJoining',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='dateofEnd',
        ),
        migrations.AddField(
            model_name='cv',
            name='companyname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.CharField(default='0', max_length=1000),
        ),
        migrations.AddField(
            model_name='cv',
            name='project',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.CharField(max_length=500),
        ),
    ]
